import Link from "next/link"

export default function AboutPage() {
  return (
    <div className="container mx-auto px-4 py-12">
      <div className="max-w-4xl mx-auto prose">
        <h2>
          Información legal
        </h2>
        <p><strong>Disclaimer, términos del servicio y política de privacidad.</strong></p>
        <p>
          Este proyecto no fue creado para ser dañino hacia los centros educativos. El objetivo no es burlar los sistemas informáticos, solo crear una web grande y con éxito que permita a la gente ser libre con sus dispositivos personales o de su pertenencia, pues ellos lo han comprado. Los creadores de esta web son anónimos y seguirán manteniendo el proyecto en pie siempre que sea posible. Podemos en cualquier momento eliminar el acceso a nuestra página a cualquier navegador, IP o dispositivo para mantener la seguridad de ZIMGo en un centro educativo. Podemos exportar ZIMGo en cualquier momento a otro dominio con el fin de que este sobreviva a un bloqueo.
          Los juegos no son creados por el equipo de ZIMGo, estos son desarrollados por terceros. Nosotros solo importamos a ZIMGo juegos con código open-source (código abierto) y dejamos cualquier referencia al autor del mismo. Los anuncios dentro de los juegos no nos pertenecen ni cobramos por ellos. Algunos de los desarrolladores de terceros de los que hemos importado sus juegos a ZIMGo son Lax1dude (Eaglercraft), geometrydashs.io (Geometry Dash), GameDistribution (Fruit Ninja, Car Racing), Emupedia (Flappy Bird, Agar.io), geometrydashlite.io (Subway Surfers), bitlifeonline.github.io/level-devil (Level Devil), Poki (Crossy Road), Crazy Games (FC 25), Krunker.io, itch.io (Friday Night Funkin, FNF Mobile by Randomana). También incrustamos páginas de terceros para ZimChat (chateagratis.net y Chateamos). Nosotros solo desarrollamos la funcionalidad de nuestra página web, el sistema de cuentas, nuevos servicios, ZimTube, ZimMusic y Unblocked Web (con la ayuda de Proxysite y Startpage). Utilizamos la API de YouTube para recibir videos en ZimTube y cargarlos como embed y para escanear y escuchar música de ZimMusic. Los otros servicios de ZIM (ZIM App, LiveConnect) son desarrollados con funciones proporcionadas por Apple Shortcuts, pero sin código de terceros. Las imágenes de los juegos pueden ser cargadas desde páginas de terceros y no nos hacemos responsables de cualquier cambio de archivo externo. Las imágenes internas de /ju3gos no nos pertenecen.
          Al permitir mostrar el nombre de usuario en partners y miembros al registrar tu cuenta de ZIMGo, permites que tu nombre de usuario sea mostrado publicamente en cualquier lugar de ZIMGo. Cuando usas los servicios de Juegos, Unblocked Web o ZimChat, no estamos bloqueando tus datos a los sitios de terceros, cada uno seguirá con su propia política de Cookies y podrá ver tu dirección IP. Los permisos que permitas en ZIMGo no se sincronizarán entre las páginas de terceros. No nos hacemos responsables de cualquier uso dañino del Unblocked Web. Los nombres y apellidos de tu cuenta se utilizan para verificar tu identidad como alumno en algún colegio con partners o personas afiliadas a ZIMGo, que buscarán en la red de tu centro para saber que eres tú. Los datos de tu cuenta (colegio, clase, número de clase, correo electrónico, teléfono, Discord) son utilizados para contactar contigo en cualquier situación importante y para ayudar a los partners y afiliados a verificarte. El proceso de creación de cuentas puede tardar hasta 7 dias. Los datos de inicio de sesión (nombre de usuario, contraseña) pueden ser vistos por cualquier programador de ZIMGo y no nos hacemos responsables de posibles filtraciones de nuestras bases de datos, por eso deberías usar una contraseña diferente en ZIMGo. El resto de información (redes sociales, notificaciones, dispositivos) se utilizará con fines estadísticos, contacto y marketing. Al crear una cuenta o usar ZIMGo aceptas esta información legal (disclaimer, términos del servicio y política de privacidad). Si estás dentro de nuestro servidor privado de Discord para usuarios registrados, aceptas que cualquier otra persona registrada o del servidor de Discord podrá ver tu cuenta de Discord e interactuar contigo. No puedes filtrar ninguna información del servidor de Discord (noticias, chat, cuentas, tickets de soporte) para publicarla con fines dañinos para ZIMGo.
          Al realizar una donación, pago o renovar una suscripción no te proporcionaremos reembolso. Si pagas alguna suscripción o servicio de ZIM, tu pago quedará registrado con tus datos reales.
          Los partners no pueden dar ninguna información de ZIMGo (cuentas, futuros servicios o planes, dominios etc.) a un miembro externo a la empresa.
          Las imágenes y bromas de Pepe son desarrolladas por artistas y animadores de ZIMGo, y no pueden ser utilizadas sin consentimiento. Cualquier tipo de comedia relaccionada con dibujos en ZIMGo no debe ser tomada en serio. Los mensajes del juego de Pepe (/pepeju3ga) son escritos por desarrolladores de ZIMGo y no queremos ofender a nadie con los mismos, solo brindar entretenimiento a quienes encuentran el secreto. El juego de Pepe, las animaciones, los mensajes, la entrada secreta y el código interno fueron cread@s por ZIMGo.
          Cualquier bloqueo de Unblocked Web, ZimChat o Juegos por red interna de un centro educativo no puede ser evadida por ZIMGo de ninguna manera. Los puntos ZimFi distribuidos por diferentes clases y colegios no pueden ser utilizados para conexión normal a internet, solo para uso de ZIMGo. Ningún miembro corporativo de los centros educativos puede revisar un dispositivo personal no gestionado por el colegio (móvil personal, tablet personal, ordenador personal, etc.) y no puede desactivar ZimFi del mismo.
          Algunos afiliados, miembros, partners y distribuidores de ZimFi pueden salir en ZIMGo si se ha permitido previamente. No todo el equipo de ZIMGo sale en miembros y partners.
        </p>
      </div>
    </div>
  )
}
